name: Scrape Deshabhimani HTML

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Deshabhimani Scraper Script
      run: npm run scrape-desha

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add deshabhimani_data.html
        git commit -m "Updated Deshabhimani HTML using Puppeteer" || echo "No changes to commit"
        git push
